"""empty message

Revision ID: 2c5bd905a321
Revises: e87dfc4c77aa
Create Date: 2019-03-30 23:34:09.579765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c5bd905a321'
down_revision = 'e87dfc4c77aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collect',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=True, comment='用户id'),
    sa.Column('article_id', sa.Integer(), nullable=True, comment='文章id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=True, comment='用户id'),
    sa.Column('article_id', sa.Integer(), nullable=True, comment='文章id'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    op.drop_table('collect')
    # ### end Alembic commands ###
