"""empty message

Revision ID: e87dfc4c77aa
Revises: 5feafc5f9f4a
Create Date: 2019-03-30 22:46:40.800375

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e87dfc4c77aa'
down_revision = '5feafc5f9f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=200), nullable=True, comment='用户id'),
    sa.Column('head_url', sa.String(length=200), nullable=True, comment='用户头像地址'),
    sa.Column('user_name', sa.String(length=100), nullable=True, comment='用户名称'),
    sa.Column('sign', sa.String(length=100), nullable=True, comment='用户签名'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('article', sa.Column('countbrowse', sa.Integer(), nullable=True))
    op.drop_column('article', 'countlike')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('countlike', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('article', 'countbrowse')
    op.drop_table('user')
    # ### end Alembic commands ###
