"""empty message

Revision ID: fe58e3cb1a4f
Revises: 
Create Date: 2019-04-08 22:52:31.387605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe58e3cb1a4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('other_name', sa.String(length=200), nullable=True, comment='昵称'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'other_name')
    # ### end Alembic commands ###
